'use client'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { SITE_CONFIG } from '@/lib/site-config'
import { globalContent } from '@/editable/content/global.content'
import { useEditableLocalAuthSession } from '@/editable/components/EditableLocalAuthForms'

export function EditableFooter(){const {session,logout}=useEditableLocalAuthSession();const year=new Date().getFullYear();return <footer className="bg-[var(--editable-footer-bg)] text-white"><div className="mx-auto max-w-[var(--editable-container)] px-5 py-14 sm:px-8 lg:px-[30px]"><div className="grid gap-10 border-b border-white/20 pb-12 lg:grid-cols-[1.35fr_1fr_1fr_1fr]"><div><Link href="/" className="editable-display text-4xl font-bold tracking-[-.06em]">{SITE_CONFIG.name}</Link><p className="mt-5 max-w-sm text-sm leading-7 text-white/65">{globalContent.footer?.description || 'A considered place to discover useful local knowledge and reliable reading material.'}</p></div><FooterColumn title="Directory" links={[["Local Directory",'/listing'],["Reference Library",'/pdf']]}/><FooterColumn title="Resources" links={[["Search",'/search'],["About",'/about'],["Contact",'/contact']]}/><FooterColumn title="Account" links={session?[["Submit",'/create']]:[["Sign in",'/login'],["Get started",'/signup']]}/>{session?<button onClick={logout} className="mt-[-18px] text-left text-sm text-white/65 hover:text-white">Logout</button>:null}</div><div className="flex flex-wrap justify-between gap-4 pt-6 text-xs text-white/55"><span>© {year} {SITE_CONFIG.name}. All rights reserved.</span><span>Built for better local knowledge.</span></div></div></footer>}
function FooterColumn({title,links}:{title:string;links:string[][]}){return <div><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--slot4-accent)]">{title}</h3><div className="mt-5 grid gap-3">{links.map(([label,href])=><Link key={href} href={href} className="inline-flex items-center gap-1 text-sm text-white/70 transition hover:text-white">{label}<ArrowUpRight className="h-3.5 w-3.5"/></Link>)}</div></div>}
