import Link from 'next/link'
import { ArrowRight, FileText, MapPin, Search } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { SITE_CONFIG } from '@/lib/site-config'
import { getEditablePostImage, postHref, toPlainText } from '@/editable/cards/PostCards'
import { EditableReveal } from '@/editable/shell/EditableReveal'

type HomeSectionProps={primaryTask:TaskKey;primaryRoute:string;posts:SitePost[];timeSections:HomeTimeSection[]}
const container='mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-[30px]'
const excerpt=(post:SitePost,n=125)=>{const content=post.content&&typeof post.content==='object'?post.content as Record<string,unknown>:{};const value=typeof content.description==='string'?content.description:post.summary||'';const clean=toPlainText(value);return clean.length>n?`${clean.slice(0,n).trim()}…`:clean}
const category=(post:SitePost)=>{const c=post.content&&typeof post.content==='object'?post.content as Record<string,unknown>:{};return typeof c.category==='string'?c.category:post.tags?.[0]||'Field note'}

function StoryCard({post,href,featured=false}:{post:SitePost;href:string;featured?:boolean}){const image=getEditablePostImage(post);return <article className={`group border-t border-[var(--editable-border)] pt-4 ${featured?'lg:border-0 lg:pt-0':''}`}><Link href={href} className="block overflow-hidden bg-[var(--slot4-media-bg)]"><img src={image} alt="" className={`w-full object-cover ${featured?'aspect-[16/10]':'aspect-[4/3]'} transition duration-700 group-hover:scale-[1.03]`}/></Link><div className="pt-4"><p className="editable-mono text-[10px] text-[var(--slot4-accent)]">{category(post)}</p><Link href={href} className={`${featured?'text-3xl sm:text-4xl':'text-xl'} editable-display mt-2 block font-bold leading-[1.06] tracking-[-.045em] transition group-hover:text-[var(--slot4-accent)]`}>{post.title}</Link><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--slot4-muted-text)]">{excerpt(post)}</p></div></article>}

export function EditableHomeHero({primaryTask,primaryRoute,posts,timeSections}:HomeSectionProps){const pool=[...posts,...timeSections.flatMap(s=>s.posts)].filter((p,i,a)=>a.findIndex(v=>(v.slug||v.id)===(p.slug||p.id))===i);const lead=pool[0];const side=pool.slice(1,3);return <section className="bg-[var(--slot4-page-bg)]"><div className={`${container} py-10 sm:py-14 lg:py-16`}><EditableReveal><div className="max-w-4xl"><p className="editable-mono text-[11px] text-[var(--slot4-accent)]">The local intelligence desk</p><h1 className="editable-display mt-3 text-5xl font-bold leading-[.95] tracking-[-.07em] sm:text-7xl lg:text-[80px]">Find the place. Keep the knowledge.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--slot4-muted-text)]">{SITE_CONFIG.name} brings dependable local services and useful reference material into one calm, readable place.</p><form action="/search" className="mt-8 flex max-w-xl border border-[var(--slot4-page-text)] bg-[var(--slot4-surface-bg)]"><Search className="m-4 h-5 w-5 shrink-0"/><input name="q" placeholder="Search the local desk" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/><button className="bg-[var(--slot4-accent)] px-5 text-sm font-semibold text-white">Search</button></form></div></EditableReveal><div className="mt-12 grid gap-8 lg:grid-cols-[1.55fr_.8fr]"><EditableReveal index={0}>{lead?<StoryCard post={lead} href={postHref(primaryTask,lead,primaryRoute)} featured/>:null}</EditableReveal><div className="grid content-start gap-7">{side.map((post,i)=><EditableReveal key={post.id||post.slug} index={i+1}><StoryCard post={post} href={postHref(primaryTask,post,primaryRoute)}/></EditableReveal>)}</div></div></div></section>}

export function EditableStoryRail({primaryTask,primaryRoute,posts}:HomeSectionProps){const cards=posts.slice(3,7);return <section className="bg-[var(--slot4-dark-bg)] text-white"><div className={`${container} py-12 sm:py-16`}><EditableReveal><div className="flex items-end justify-between gap-4"><div><p className="editable-mono text-[10px] text-[var(--slot4-accent)]">Start here</p><h2 className="editable-display mt-2 text-3xl font-bold tracking-[-.05em] sm:text-4xl">The essential shelves</h2></div><Link href={primaryRoute} className="inline-flex items-center gap-2 text-sm font-semibold text-white/80 hover:text-white">See the collection <ArrowRight className="h-4 w-4"/></Link></div></EditableReveal><div className="mt-8 grid gap-px bg-white/20 sm:grid-cols-2 lg:grid-cols-4">{cards.map((post,i)=><EditableReveal key={post.id||post.slug} index={i}><Link href={postHref(primaryTask,post,primaryRoute)} className="block bg-[var(--slot4-dark-bg)] p-5 transition hover:bg-white hover:text-[var(--slot4-page-text)]"><FileText className="h-6 w-6 text-[var(--slot4-accent)]"/><p className="mt-8 text-[11px] font-semibold uppercase tracking-[.13em] text-white/55">{category(post)}</p><h3 className="editable-display mt-2 text-xl font-bold leading-tight tracking-[-.035em]">{post.title}</h3></Link></EditableReveal>)}</div></div></section>}

export function EditableMagazineSplit({primaryTask,primaryRoute,posts}:HomeSectionProps){const cards=posts.slice(7,13);return <section><div className={`${container} py-16 sm:py-20 lg:py-[120px]`}><EditableReveal><div className="grid gap-6 border-b border-[var(--editable-border)] pb-7 lg:grid-cols-[1fr_1fr]"><div><p className="editable-mono text-[10px] text-[var(--slot4-accent)]">Local Directory</p><h2 className="editable-display mt-2 text-4xl font-bold tracking-[-.055em]">Useful names, clearly presented.</h2></div><p className="self-end text-base leading-7 text-[var(--slot4-muted-text)]">A practical edit of the places and people worth knowing, with direct information when you need it.</p></div></EditableReveal><div className="mt-8 grid gap-x-8 gap-y-10 md:grid-cols-2 lg:grid-cols-3">{cards.map((post,i)=><EditableReveal key={post.id||post.slug} index={i}><StoryCard post={post} href={postHref(primaryTask,post,primaryRoute)}/></EditableReveal>)}</div></div></section>}

export function EditableTimeCollections({primaryTask,primaryRoute,posts,timeSections}:HomeSectionProps){const section=timeSections.find(s=>s.posts.length);const cards=(section?.posts.length?section.posts:posts.slice(13,21)).slice(0,4);if(!cards.length)return null;return <section className="bg-[var(--slot4-warm)]"><div className={`${container} py-16 sm:py-20 lg:py-[120px]`}><EditableReveal><p className="editable-mono text-[10px] text-[var(--slot4-accent)]">Reference Library</p><h2 className="editable-display mt-2 max-w-2xl text-4xl font-bold leading-[1.03] tracking-[-.055em] sm:text-5xl">Read, download, return when it matters.</h2></EditableReveal><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{cards.map((post,i)=><EditableReveal key={post.id||post.slug} index={i}><Link href={postHref(primaryTask,post,primaryRoute)} className="block border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] p-6 transition hover:border-[var(--slot4-accent)]"><FileText className="h-8 w-8 text-[var(--slot4-accent)]"/><p className="editable-mono mt-12 text-[10px] text-[var(--slot4-muted-text)]">Reference note</p><h3 className="editable-display mt-2 text-xl font-bold leading-tight tracking-[-.035em]">{post.title}</h3><p className="mt-4 text-sm leading-6 text-[var(--slot4-muted-text)]">{excerpt(post,90)}</p></Link></EditableReveal>)}</div></div></section>}

export function EditableHomeCta(){return <section className="bg-[var(--slot4-accent)] text-white"><div className={`${container} grid gap-8 py-14 sm:py-16 lg:grid-cols-[1fr_auto] lg:items-end`}><div><p className="editable-mono text-[10px] text-white/70">Your knowledge belongs here</p><h2 className="editable-display mt-2 max-w-2xl text-4xl font-bold tracking-[-.055em] sm:text-5xl">Put a useful place or reference on the record.</h2></div><Link href="/create" className="inline-flex items-center justify-center gap-2 border border-white px-5 py-3 text-sm font-semibold hover:bg-white hover:text-[var(--slot4-accent)]">Submit an entry <ArrowRight className="h-4 w-4"/></Link></div></section>}
